services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    image: ai-challenge-mcp:day10
    container_name: mcp-server-day10
    ports:
      - "8004:8004"  # HTTP API
    environment:
      - MODEL_TIMEOUT_SECONDS=60
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
    networks:
      - mcp-network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  mcp-network:
    driver: bridge
