# Agent Configuration
agents:
  code_generator:
    name: "CodeGenerator"
    description: "Generates code based on prompts"
    enabled: true
    
  code_reviewer:
    name: "CodeReviewer"
    description: "Reviews code for quality and best practices"
    enabled: true

  token_analyzer:
    name: "TokenAnalyzer"
    description: "Analyzes token usage and efficiency"
    enabled: true

defaults:
  max_tokens: 4096
  temperature: 0.7
  timeout: 30

